# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2023-11-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krydsliste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
