# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('barcard_file', models.FileField(blank=True, upload_to='barcard')),
                ('mixing_file', models.FileField(blank=True, upload_to='mixing')),
                ('source_file', models.FileField(blank=True, upload_to='source')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('serving', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('secret', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Sprut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Drink')),
            ],
        ),
        migrations.AddField(
            model_name='barcard',
            name='drinks',
            field=models.ManyToManyField(to='drinks.Drink'),
        ),
    ]
