# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprut',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
