# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('drinks', models.ManyToManyField(to='drinks.Drink')),
            ],
        ),
    ]
